In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ephre\Documents\Telecommunication-dataset-analysis\Data\Week2_challenge_data_source(CSV).csv")

In [3]:
df.sample(4)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
122920,6.917538e+18,4/28/2019 5:12,42.0,4/29/2019 5:12,939.0,86399.0,2.082010e+14,3.368240e+10,3.564891e+13,U10624C,...,4162773.0,21757958.0,12308619.0,19717239.0,145324053.0,4603332.0,384505708.0,7099296.0,54984030.0,173134967.0
10848,1.304243e+19,4/24/2019 17:11,542.0,4/25/2019 0:22,90.0,25906.0,2.082010e+14,3.369822e+10,3.567601e+13,L70442C,...,6932816.0,7588454.0,10581012.0,15445326.0,142465547.0,16344748.0,682906.0,11544216.0,52027532.0,172032235.0
49025,7.349883e+18,4/25/2019 7:46,894.0,4/26/2019 9:46,941.0,93601.0,2.082003e+14,3.362291e+10,3.590421e+13,L85930A,...,12644820.0,12910765.0,9348413.0,13473814.0,146517269.0,6292348.0,662420673.0,11680154.0,46020821.0,182456035.0
9478,7.421941e+18,4/24/2019 16:16,975.0,4/25/2019 0:27,942.0,29457.0,2.082010e+14,3.367029e+10,3.530451e+13,D11100A,...,18922750.0,20704951.0,19836928.0,8423945.0,343271319.0,4125741.0,407201185.0,7355111.0,45366923.0,385790079.0

In [5]:
df.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')